version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "APIGatewayQuarkusDemo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-p792n280trsk"
s3_prefix = "APIGatewayQuarkusDemo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
